export const API_ENDPOINTS = [
  {
    id: 'series-list',
    tag: 'Series',
    title: 'List all series',
    method: 'GET',
    path: '/api/series',
    description: 'Fetch every series without pagination.',
    notes: 'Useful for quick dropdowns and tiny datasets.',
    pathParams: [],
    queryParams: [],
    hasBody: false,
    sampleBody: null,
  },
  {
    id: 'series-search',
    tag: 'Series',
    title: 'Search series',
    method: 'GET',
    path: '/api/series/search',
    description: 'Filter by name, type, and year range.',
    notes: 'Series type accepts RIDER or SENTAI.',
    pathParams: [],
    queryParams: [
      { name: 'name', placeholder: 'Kuuga', example: 'Kuuga' },
      { name: 'type', placeholder: 'RIDER', example: 'RIDER' },
      { name: 'yearFrom', placeholder: '2000', example: '2000' },
      { name: 'yearTo', placeholder: '2025', example: '2025' },
      { name: 'size', placeholder: '20', example: '20' },
      { name: 'page', placeholder: '0', example: '0' },
    ],
    hasBody: false,
    sampleBody: null,
  },
  {
    id: 'series-create',
    tag: 'Series',
    title: 'Create series',
    method: 'POST',
    path: '/api/series',
    description: 'Create a new series entity.',
    notes: 'Name and type are required. Optional image fields support base64 or URL.',
    pathParams: [],
    queryParams: [],
    hasBody: true,
    sampleBody: {
      name: 'Kamen Rider Example',
      type: 'RIDER',
      yearStart: 2026,
      yearEnd: 2027,
      description: 'Example series entry for docs.',
      seriesImageUrl: 'https://example.com/series.jpg',
    },
  },
  {
    id: 'series-detail',
    tag: 'Series',
    title: 'Series detail',
    method: 'GET',
    path: '/api/series/{id}/detail',
    description: 'Get series plus full character and episode arrays.',
    notes: 'Great for one-shot detail pages.',
    pathParams: [{ name: 'id', placeholder: 'Series id', example: '1' }],
    queryParams: [],
    hasBody: false,
    sampleBody: null,
  },
  {
    id: 'characters-list',
    tag: 'Characters',
    title: 'List all characters',
    method: 'GET',
    path: '/api/characters',
    description: 'Get every character in the database.',
    notes: 'Unpaged endpoint.',
    pathParams: [],
    queryParams: [],
    hasBody: false,
    sampleBody: null,
  },
  {
    id: 'characters-search',
    tag: 'Characters',
    title: 'Search characters',
    method: 'GET',
    path: '/api/characters/search',
    description: 'Search by name, role, color, and series.',
    notes: 'Role accepts MAIN, SECONDARY, EXTRA, SIXTH.',
    pathParams: [],
    queryParams: [
      { name: 'name', placeholder: 'Ichigo', example: 'Ichigo' },
      { name: 'role', placeholder: 'MAIN', example: 'MAIN' },
      { name: 'color', placeholder: 'Red', example: 'Red' },
      { name: 'seriesId', placeholder: '1', example: '1' },
      { name: 'size', placeholder: '20', example: '20' },
      { name: 'page', placeholder: '0', example: '0' },
    ],
    hasBody: false,
    sampleBody: null,
  },
  {
    id: 'characters-create',
    tag: 'Characters',
    title: 'Create character',
    method: 'POST',
    path: '/api/characters',
    description: 'Create a character linked to a series.',
    notes: 'Name, role, and seriesId are required.',
    pathParams: [],
    queryParams: [],
    hasBody: true,
    sampleBody: {
      name: 'Kamen Rider Sample',
      role: 'MAIN',
      color: 'Red',
      seriesId: 1,
      characterImageUrl: 'https://example.com/rider.jpg',
    },
  },
  {
    id: 'characters-by-series-role',
    tag: 'Characters',
    title: 'Characters by series and role',
    method: 'GET',
    path: '/api/characters/series/{seriesId}/role/{role}',
    description: 'Filter character list by series and role.',
    notes: 'Ideal for roster widgets and role-specific galleries.',
    pathParams: [
      { name: 'seriesId', placeholder: 'Series id', example: '1' },
      { name: 'role', placeholder: 'MAIN', example: 'MAIN' },
    ],
    queryParams: [],
    hasBody: false,
    sampleBody: null,
  },
  {
    id: 'episodes-by-series',
    tag: 'Episodes',
    title: 'Episodes by series',
    method: 'GET',
    path: '/api/episodes/series/{seriesId}',
    description: 'List all episodes for one series.',
    notes: 'Use this for episode tabs and watch-order pages.',
    pathParams: [{ name: 'seriesId', placeholder: 'Series id', example: '1' }],
    queryParams: [],
    hasBody: false,
    sampleBody: null,
  },
  {
    id: 'episodes-search',
    tag: 'Episodes',
    title: 'Search episodes',
    method: 'GET',
    path: '/api/episodes/search',
    description: 'Search by title, series, and date range.',
    notes: 'Dates are ISO format: YYYY-MM-DD.',
    pathParams: [],
    queryParams: [
      { name: 'seriesId', placeholder: '1', example: '1' },
      { name: 'title', placeholder: 'Final Battle', example: 'Final Battle' },
      { name: 'fromDate', placeholder: '2020-01-01', example: '2020-01-01' },
      { name: 'toDate', placeholder: '2026-12-31', example: '2026-12-31' },
      { name: 'size', placeholder: '20', example: '20' },
      { name: 'page', placeholder: '0', example: '0' },
    ],
    hasBody: false,
    sampleBody: null,
  },
  {
    id: 'episodes-create',
    tag: 'Episodes',
    title: 'Create episode',
    method: 'POST',
    path: '/api/episodes',
    description: 'Create an episode for a series.',
    notes: 'episodeNumber, title, and seriesId are required.',
    pathParams: [],
    queryParams: [],
    hasBody: true,
    sampleBody: {
      episodeNumber: 1,
      title: 'Arrival',
      airDate: '2026-01-12',
      seriesId: 1,
      imageUrl: 'https://example.com/ep1.jpg',
    },
  },
  {
    id: 'episode-by-number',
    tag: 'Episodes',
    title: 'Episode by number',
    method: 'GET',
    path: '/api/episodes/series/{seriesId}/number/{episodeNumber}',
    description: 'Lookup a specific episode by series and number.',
    notes: 'Useful for canonical episode URLs.',
    pathParams: [
      { name: 'seriesId', placeholder: 'Series id', example: '1' },
      { name: 'episodeNumber', placeholder: '1', example: '1' },
    ],
    queryParams: [],
    hasBody: false,
    sampleBody: null,
  },
  {
    id: 'forms-by-character',
    tag: 'Forms',
    title: 'Forms by character',
    method: 'GET',
    path: '/api/forms/character/{characterId}',
    description: 'List all forms for a character.',
    notes: 'Use /final variant for final forms only.',
    pathParams: [{ name: 'characterId', placeholder: 'Character id', example: '1' }],
    queryParams: [],
    hasBody: false,
    sampleBody: null,
  },
  {
    id: 'forms-create',
    tag: 'Forms',
    title: 'Create form',
    method: 'POST',
    path: '/api/forms',
    description: 'Create a transformation form for a character.',
    notes: 'name and characterId are required.',
    pathParams: [],
    queryParams: [],
    hasBody: true,
    sampleBody: {
      name: 'Ultimate Form',
      powerType: 'Light',
      isFinalForm: true,
      characterId: 1,
      formImageUrl: 'https://example.com/form.jpg',
    },
  },
  {
    id: 'search-global',
    tag: 'Search',
    title: 'Global text search',
    method: 'GET',
    path: '/api/search',
    description: 'Search series, characters, and episodes together.',
    notes: 'q is required, limit is optional (1-100).',
    pathParams: [],
    queryParams: [
      { name: 'q', placeholder: 'kuuga', example: 'kuuga' },
      { name: 'limit', placeholder: '10', example: '10' },
    ],
    hasBody: false,
    sampleBody: null,
  },
  {
    id: 'wiki-sync-all',
    tag: 'Admin',
    title: 'Sync all wiki series',
    method: 'POST',
    path: '/api/admin/wiki/sync/all',
    description: 'Import Rider and Sentai series from Fandom.',
    notes: 'Admin utility endpoint. Can take longer depending on external API latency.',
    pathParams: [],
    queryParams: [],
    hasBody: false,
    sampleBody: null,
  },
  {
    id: 'wiki-sync-characters',
    tag: 'Admin',
    title: 'Sync characters for series',
    method: 'POST',
    path: '/api/admin/wiki/sync/characters/{seriesId}',
    description: 'Import character list for one existing series.',
    notes: 'The series must exist first (run series sync endpoint before this one).',
    pathParams: [{ name: 'seriesId', placeholder: 'Series id', example: '1' }],
    queryParams: [],
    hasBody: false,
    sampleBody: null,
  },
]
